### ISSUE TITLE
The size of image zoom

### ISSUE THREAD

**Issue by shuaicaihongtu** [tecnickcom/inedi#1]
HELLO! i have some problem with inedi demo.1.why the size of  enlarged image is （SIZE * 2 ^ ZK） - （2 ^ ZK-1）not （SIZE * 2 ^ ZK）?

**Comment by shuaicaihongtu** [comment]
If I want to use edge detection results to distinguish between edge pixels and non-edge pixels, then how should I change the condition?

**Comment by nicolaasuni** [comment]
The size of the final enlarged image is that way because it is a hole-filling method. So for example, if your image is 2x2 pixel, you'll end up with 3x3 pixel image (one pixel added in the center):
```
 0 0
  x
 0 0
```
